'GPG_KEY': 'E3FF2839C048B25C084DEBE9B26995E310250568'
'HOME': '/root'
'HOSTNAME': 'c7726e688ff0'
'LANG': 'C.UTF-8'
'MAPBOX_ACCESS_TOKEN': 'pk.eyJ1IjoidGFuanVua2Fpc3BkaWdpdGFsIiwiYSI6ImNrOHBqODR0bzFrcm4zZ3FveGgwdjBpeDQifQ.TtZsio5IHPT7b1TCpvCJyQ'
'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'PYTHON_GET_PIP_SHA256': '8006625804f55e1bd99ad4214fd07082fee27a1c35945648a58f9087a714e9d4'
'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/4be3fe44ad9dedc028629ed1497052d65d281b8e/get-pip.py'
'PYTHON_PIP_VERSION': '21.0.1'
'PYTHON_VERSION': '3.9.1'
'TERM': 'xterm'