"""init table

Revision ID: 4486db09cf7f
Revises: 
Create Date: 2021-03-08 03:53:59.482235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4486db09cf7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationlist',
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('notification_no', sa.String(), nullable=False),
    sa.Column('notification_date', sa.DateTime(), nullable=False),
    sa.Column('contract_acct', sa.String(), nullable=False),
    sa.Column('cause_code', sa.String(), nullable=True),
    sa.Column('meter_no', sa.String(), nullable=False),
    sa.Column('prediction', sa.Boolean(), nullable=True),
    sa.Column('consecutive_false', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('notification_no')
    )
    op.create_index(op.f('ix_notificationlist_contract_acct'), 'notificationlist', ['contract_acct'], unique=False)
    op.create_index(op.f('ix_notificationlist_meter_no'), 'notificationlist', ['meter_no'], unique=False)
    op.create_index(op.f('ix_notificationlist_notification_date'), 'notificationlist', ['notification_date'], unique=False)
    op.create_index(op.f('ix_notificationlist_notification_no'), 'notificationlist', ['notification_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificationlist_notification_no'), table_name='notificationlist')
    op.drop_index(op.f('ix_notificationlist_notification_date'), table_name='notificationlist')
    op.drop_index(op.f('ix_notificationlist_meter_no'), table_name='notificationlist')
    op.drop_index(op.f('ix_notificationlist_contract_acct'), table_name='notificationlist')
    op.drop_table('notificationlist')
    # ### end Alembic commands ###
