"""add a probability feild to ZQRaw

Revision ID: 597872ae37c5
Revises: 82cc6d30afca
Create Date: 2021-03-08 06:28:14.738334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597872ae37c5'
down_revision = '82cc6d30afca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zq_raw', sa.Column('probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zq_raw', 'probability')
    # ### end Alembic commands ###
