"""add a table to hold raw notifications

Revision ID: 82cc6d30afca
Revises: 4486db09cf7f
Create Date: 2021-03-08 06:19:12.073447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cc6d30afca'
down_revision = '4486db09cf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zq_raw',
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('notification_no', sa.String(), nullable=False),
    sa.Column('notification_date', sa.DateTime(), nullable=False),
    sa.Column('contract_acct', sa.String(), nullable=False),
    sa.Column('cause_code', sa.String(), nullable=True),
    sa.Column('meter_no', sa.String(), nullable=False),
    sa.Column('prediction', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('notification_no')
    )
    op.create_index(op.f('ix_zq_raw_contract_acct'), 'zq_raw', ['contract_acct'], unique=False)
    op.create_index(op.f('ix_zq_raw_meter_no'), 'zq_raw', ['meter_no'], unique=False)
    op.create_index(op.f('ix_zq_raw_notification_date'), 'zq_raw', ['notification_date'], unique=False)
    op.create_index(op.f('ix_zq_raw_notification_no'), 'zq_raw', ['notification_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zq_raw_notification_no'), table_name='zq_raw')
    op.drop_index(op.f('ix_zq_raw_notification_date'), table_name='zq_raw')
    op.drop_index(op.f('ix_zq_raw_meter_no'), table_name='zq_raw')
    op.drop_index(op.f('ix_zq_raw_contract_acct'), table_name='zq_raw')
    op.drop_table('zq_raw')
    # ### end Alembic commands ###
