"""add shap column in notificationlist

Revision ID: a90a742e63b3
Revises: e107d74ba5a4
Create Date: 2021-03-28 13:12:12.454801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90a742e63b3'
down_revision = 'e107d74ba5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificationlist', sa.Column('shap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificationlist', 'shap')
    # ### end Alembic commands ###
