"""change JSON to JSONB

Revision ID: b7e522872a40
Revises: a90a742e63b3
Create Date: 2021-03-31 01:42:46.986813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e522872a40'
down_revision = 'a90a742e63b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
