"""Add 12 seperate months for consec_f in Cell

Revision ID: e107d74ba5a4
Revises: fd65e04270be
Create Date: 2021-03-12 08:05:58.205064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e107d74ba5a4'
down_revision = 'fd65e04270be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificationlist', sa.Column('consec_false_10month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_11month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_12month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_1month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_2month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_3month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_4month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_5month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_6month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_7month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_8month', sa.Integer(), nullable=True))
    op.add_column('notificationlist', sa.Column('consec_false_9month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificationlist', 'consec_false_9month')
    op.drop_column('notificationlist', 'consec_false_8month')
    op.drop_column('notificationlist', 'consec_false_7month')
    op.drop_column('notificationlist', 'consec_false_6month')
    op.drop_column('notificationlist', 'consec_false_5month')
    op.drop_column('notificationlist', 'consec_false_4month')
    op.drop_column('notificationlist', 'consec_false_3month')
    op.drop_column('notificationlist', 'consec_false_2month')
    op.drop_column('notificationlist', 'consec_false_1month')
    op.drop_column('notificationlist', 'consec_false_12month')
    op.drop_column('notificationlist', 'consec_false_11month')
    op.drop_column('notificationlist', 'consec_false_10month')
    # ### end Alembic commands ###
